name: PR Check

on:
  pull_request:
    branches: [ main ]

permissions:
  id-token: write
  contents: read
  pull-requests: write

jobs:
  python_ci:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.10"

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install ruff mypy 

      - name: Lint with ruff
        run: ruff check .

      - name: Type-check with mypy
        run: mypy .

  terraform_check:
    needs: python_ci
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Authenticate to Google Cloud
        id: auth
        uses: google-github-actions/auth@v2
        with:
          token_format: "access_token"
          project_id: ${{ secrets.PROJECT_ID_DEV }}
          workload_identity_provider: >-
            projects/${{ secrets.PROJECT_NUMBER_DEV }}/locations/global/workloadIdentityPools/github-actions/providers/github-actions
          service_account: >-
            github-actions-001@${{ secrets.PROJECT_ID_DEV }}.iam.gserviceaccount.com

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v3
        with:
          terraform_version: 1.11.4

      - name: Terraform fmt
        id: fmt
        run: terraform fmt -check
        continue-on-error: true

      - name: Terraform Init
        run: terraform init

      - name: Terraform Validate
        id: validate
        run: terraform validate -no-color

      - name: Terraform Plan
        id: plan
        run: terraform plan -no-color
        continue-on-error: true
